#!/usr/bin/env bash
pushd ~/Projects/Linux-tools-by-Frodo/ListenToFavoriteRadio
## Collect the files in the array $files
files=( ./Radio/{*,**/*}.m3u )
## Enable extended globbing. This lets us use @(foo|bar) to
## match either 'foo' or 'bar'.
shopt -s extglob

## Start building the string to match against.
string="@(${files[0]}"
## Add the rest of the files to the string
for((i=1;i<${#files[@]};i++))
do
    string+="|${files[$i]}"
done
## Close the parenthesis. $string is now @(file1|file2|...|fileN)
string+=")"

## Show the menu. This will list all files and the string "quit"
select file in "${files[@]}" "/home/cirno/Library/Музыка/*.mp3" "quit"
do
    case $file in
    ## If the choice is one of the files (if it matches $string)
    $string)
        ## Do something here
        echo "$file"
##	mpg123 -o pulse -@ "$file"
        mpv --ao=pulse "$file"
        ## Uncomment this line if you don't want the menu to
        ## be shown again
        #break;
	break;
	;;
    "/home/cirno/Library/Музыка/*.mp3")
	mpg123 -o pulse -C -z /home/cirno/Library/Музыка/*.mp3
	break;
	;;
    "quit")
        ## Exit
        exit;;
    *)
        file=""
        echo "Please choose a number from 1 to $((${#files[@]}+1))";;
    esac
done
popd
